import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import ts from 'typescript';

const source = await readFile(new URL('../src/world/oceanDetailTexture.ts', import.meta.url), 'utf8');
const compiled = ts.transpileModule(source, {
  compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ES2022 },
}).outputText.replace(/\bfrom\s+(["'])([^"']+)\1/g, (_match, _quote, specifier) => {
  const name = specifier.startsWith('@babylonjs/core/') && !specifier.endsWith('.js') ? `${specifier}.js` : specifier;
  return `from ${JSON.stringify(import.meta.resolve(name))}`;
});
const { generateOceanDetailData, OCEAN_DETAIL_TEXTURE_SIZE: size,
  OCEAN_DETAIL_SLOPE_SCALE: scale } = await import(`data:text/javascript;base64,${Buffer.from(compiled).toString('base64')}`);

test('cached wind-sea detail has zero mean slope and directional small-wave energy', () => {
  const data = generateOceanDetailData();
  assert.equal(generateOceanDetailData(), data, 'scene restarts reuse the generated bytes');
  assert.equal(data.length, size * size * 4);
  // RGBA plus every mip fits below half a megabyte per GPU texture.
  assert.ok(data.byteLength * 4 / 3 < 512 * 1024);
  let sumX = 0, sumZ = 0, alongVariance = 0, acrossVariance = 0, crestVariance = 0;
  for (let offset = 0; offset < data.length; offset += 4) {
    const x = (data[offset] / 255 * 2 - 1) * scale;
    const z = (data[offset + 1] / 255 * 2 - 1) * scale;
    sumX += x; sumZ += z;
    alongVariance += (x * 0.8 + z * 0.6) ** 2;
    acrossVariance += (x * -0.6 + z * 0.8) ** 2;
    crestVariance += (data[offset + 2] / 255 - 0.5) ** 2;
    assert.ok(data[offset] > 0 && data[offset] < 255 && data[offset + 1] > 0 && data[offset + 1] < 255,
      'encoding must preserve gradients without clipping their peaks');
    assert.equal(data[offset + 3], 255);
  }
  const count = size * size;
  assert.ok(Math.abs(sumX / count) < 0.0001 && Math.abs(sumZ / count) < 0.0001,
    'periodic waves cannot introduce a permanent water-surface tilt');
  assert.ok(alongVariance > acrossVariance * 1.5, 'wind-sea slopes should favour the wind direction');
  const rms = Math.sqrt((alongVariance + acrossVariance) / count);
  assert.ok(rms > 0.035 && rms < 0.15, 'detail slopes represent gentle wind chop');
  assert.ok(crestVariance / count > 0.008, 'crest texture must retain irregular spatial structure');
});

test('wrapping the tile preserves ordinary neighbouring-texel gradients', () => {
  const data = generateOceanDetailData();
  for (const axis of ['x', 'z']) for (const channel of [0, 1, 2]) {
    let interiorDifference = 0, seamDifference = 0;
    for (let row = 0; row < size; row++) for (let column = 0; column < size; column++) {
      const nextRow = axis === 'z' ? (row + 1) % size : row;
      const nextColumn = axis === 'x' ? (column + 1) % size : column;
      const current = data[(row * size + column) * 4 + channel];
      const next = data[(nextRow * size + nextColumn) * 4 + channel];
      const difference = (next - current) ** 2;
      if ((axis === 'x' ? column : row) === size - 1) seamDifference += difference;
      else interiorDifference += difference;
    }
    const seamMean = seamDifference / size;
    const interiorMean = interiorDifference / (size * (size - 1));
    assert.ok(seamMean < interiorMean * 2.0,
      `${axis} wrap in channel ${channel} must not produce a texture-border jump`);
  }
});
